spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/RM
  data:
    redis:
      host: localhost
      port: 6379
      password: redis_password